//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sylabus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study_programme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Study_programme()
        {
            this.Ours_grid = new HashSet<Ours_grid>();
        }
    
        public int Id_study_program { get; set; }
        public Nullable<int> Faculty { get; set; }
        public string Study_mode { get; set; }
        public string Study_degree { get; set; }
        public string Name_PL { get; set; }
        public string Name_ENG { get; set; }
    
        public virtual Faculty Faculty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ours_grid> Ours_grid { get; set; }
    }
}
