//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylabusWMI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sylabusWMIEntities : DbContext
    {
        public sylabusWMIEntities()
            : base("name=sylabusWMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Elements_in_template> Elements_in_template { get; set; }
        public virtual DbSet<Elements_value> Elements_value { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Ours_grid> Ours_grid { get; set; }
        public virtual DbSet<Ours_grid_elements> Ours_grid_elements { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Study_programme> Study_programme { get; set; }
        public virtual DbSet<Sylabu> Sylabus { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Template_elements> Template_elements { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
