//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylabusWMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements_value
    {
        public int Id_value { get; set; }
        public string Value_PL { get; set; }
        public Nullable<int> Elements_template { get; set; }
        public string Sylabus { get; set; }
        public string Template { get; set; }
        public string Value_EN { get; set; }
    
        public virtual Elements_in_template Elements_in_template { get; set; }
        public virtual Sylabu Sylabu { get; set; }
        public virtual Template Template1 { get; set; }
    }
}
