//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylabusWMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_elements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template_elements()
        {
            this.Elements_in_template = new HashSet<Elements_in_template>();
        }
    
        public int Id { get; set; }
        public string Elements_name { get; set; }
        public string Tempalate { get; set; }
        public Nullable<bool> Obligatory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elements_in_template> Elements_in_template { get; set; }
    }
}
