//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylabusWMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wartosc_Elementu
    {
        public int Id_wartosci { get; set; }
        public string Vartość { get; set; }
        public Nullable<int> Element_template { get; set; }
        public string Sylabus { get; set; }
    
        public virtual Elementy_template Elementy_template { get; set; }
        public virtual Sylabu Sylabu { get; set; }
    }
}
