//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sylabusWMIEntities : DbContext
    {
        public sylabusWMIEntities()
            : base("name=sylabusWMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Elementy_siatki> Elementy_siatki { get; set; }
        public virtual DbSet<Elementy_template> Elementy_template { get; set; }
        public virtual DbSet<Program_studiow> Program_studiow { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Siatka_godzin> Siatka_godzin { get; set; }
        public virtual DbSet<Sylabu> Sylabus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicies { get; set; }
        public virtual DbSet<Wartosc_Elementu> Wartosc_Elementu { get; set; }
        public virtual DbSet<Wydzial> Wydzials { get; set; }
    }
}
