//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements_in_template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Elements_in_template()
        {
            this.Elements_value = new HashSet<Elements_value>();
        }
    
        public int Id { get; set; }
        public string Template { get; set; }
        public Nullable<int> Element { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Template Template1 { get; set; }
        public virtual Template_elements Template_elements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elements_value> Elements_value { get; set; }
    }
}
