//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elementy_siatki
    {
        public int Id { get; set; }
        public string Sylabus { get; set; }
        public string Siatka { get; set; }
    
        public virtual Siatka_godzin Siatka_godzin { get; set; }
        public virtual Sylabu Sylabu { get; set; }
    }
}
