//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ours_grid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ours_grid()
        {
            this.Ours_grid_elements = new HashSet<Ours_grid_elements>();
        }
    
        public string Id_grid { get; set; }
        public Nullable<int> Study_programme { get; set; }
        public Nullable<int> Recruitment_year { get; set; }
        public Nullable<int> Faculty { get; set; }
    
        public virtual Faculty Faculty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ours_grid_elements> Ours_grid_elements { get; set; }
        public virtual Study_programme Study_programme1 { get; set; }
    }
}
