//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string Id_roli { get; set; }
        public string Nazwa_Roli { get; set; }
        public string Opis_roli { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
