//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siatka_godzin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siatka_godzin()
        {
            this.Elementy_siatki = new HashSet<Elementy_siatki>();
            this.Sylabus = new HashSet<Sylabu>();
        }
    
        public string Id_siatki { get; set; }
        public string Program_studiow { get; set; }
        public string Rok_rekrutacji { get; set; }
        public string Kierunek { get; set; }
        public string Semestr { get; set; }
        public string Wydział { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elementy_siatki> Elementy_siatki { get; set; }
        public virtual Program_studiow Program_studiow1 { get; set; }
        public virtual Wydzial Wydzial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sylabu> Sylabus { get; set; }
    }
}
