//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sylabu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sylabu()
        {
            this.Elementy_siatki = new HashSet<Elementy_siatki>();
            this.Elementy_template = new HashSet<Elementy_template>();
            this.Wartosc_Elementu = new HashSet<Wartosc_Elementu>();
        }
    
        public string Id_sylabusa { get; set; }
        public string Kod_przedmiotu { get; set; }
        public string Template { get; set; }
        public string Siatka { get; set; }
        public Nullable<int> Wykladowca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elementy_siatki> Elementy_siatki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elementy_template> Elementy_template { get; set; }
        public virtual Siatka_godzin Siatka_godzin { get; set; }
        public virtual Template Template1 { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wartosc_Elementu> Wartosc_Elementu { get; set; }
    }
}
