//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wydzial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wydzial()
        {
            this.Program_studiow = new HashSet<Program_studiow>();
            this.Siatka_godzin = new HashSet<Siatka_godzin>();
        }
    
        public string Id_jednostki { get; set; }
        public string Nazwa_PL { get; set; }
        public string Nazwa_ENG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program_studiow> Program_studiow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siatka_godzin> Siatka_godzin { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
    }
}
